version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: bitrix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bitrix
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
    tmpfs:
      - /var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitrix-php
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: bitrix-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bitrix-pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
